## color codes
# failed = §c
# success = §a
# time = §f
# player = §f
# group = §6

## flags
# {anyPlayer}
# {group}
# {time}

logs:
  - type: failed_invalid
    message: "§cUnknown command. Use \"/group help\" for help."

  - type: failed_parse
    message: "§cError, something went wrong."

  - type: failed_player_not_found
    message: "§cPlayer §f{anyPlayer}§c not found."

  - type: failed_group_not_found
    message: "§cGroup §6{group}§c not found."

  - type: failed_player_not_in_group
    message: "§f{anyPlayer}§c belongs to a different group."

  - type: failed_add_already_member
    message: "§f{anyPlayer}§c is already member of group §6{group}§c."

  - type: failed_add_player_to_group
    message: "§cFailed to add §f{anyPlayer}§c to the group."

  - type: failed_player_no_group
    message: "§f{anyPlayer}§c has no group."

  - type: failed_only_player
    message: "§cOnly players can execute this command."

  - type: failed_group_already_exists
    message: "§cGroup §6{group}§c already exists."

  - type: success_create
    message: "§aGroup §6[{group}]§a successfully created."

  - type: success_add
    message: "§aSuccessfully added §f{anyPlayer}§a to the group."

  - type: success_remove
    message: "§aSuccessfully removed §f{anyPlayer}§a from the group."

  - type: success_remove_after
    message: "§aSuccess! §f{anyPlayer}§a will be removed after §f{time}§a."

  - type: time_expired
    message: "§fYour time expired. You were removed from your group."