## color codes
# warning = §c
# success = §a
# time = §f
# group = §6
# player count = §8

## flags
# {player}
# {group}
# {time}
# {count}

logs:
  - type: invalid_command
    message: "§cUnknown command. Use \"/group help\" for help."

  - type: invalid_input
    message: "§cInvalid input. Use \"/group help\" for help."

  - type: group_not_found
    message: "§6[{group}]§c not found."

  - type: group_already_exists
    message: "§6[{group}]§c already exists."

  - type: group_created
    message: "§6[{group}]§a created successfully."

  - type: group_not_created
    message: "§cFailed to create §6[{group}]§c."

  - type: player_not_found
    message: "§c{player} was not found."

  - type: player_already_in_that_group
    message: "§c{player} is already a member of §6[{group}]§c."

  - type: player_added_to_group
    message: "§a{player} is now a member of §6[{group}]§a."

  - type: player_not_added_to_group
    message: "§cFailed to add {player} to §6[{group}]§c."

  - type: player_not_in_group
    message: "§c{player} is no member of a group yet."

  - type: sender_is_not_player
    message: "§cOnly players have permissions to execute this command."

  - type: group_or_player_not_found
    message: "§cGroup §6[{group}]§c or player {player} was not found."

  - type: player_removed_from_group
    message: "§a{player} got removed from §6[{group}]§a."

  - type: player_not_removed_from_group
    message: "§cFailed to remove {player} from §6[{group}]§c."

  - type: player_removed_from_group_for_time
    message: "§a{player} will be removed from §6[{group}]§a in §f{time}."

  - type: you_got_removed_from_group
    message: "§cYou got removed from §6[{group}]§c. You are now in group §6[Player]§c."

  - type: player_joined_the_server
    message: "§f[§6{group}§f] {player} §ajoined the server."

infos:
  - type: show_group_info_header
    message: "§2Group: §6[{group}]§a | players ({count})\n"

  - type: show_player_info
    message: "§a- {player} §7{time}\n"

  - type: list_all_groups_info_header
    message: "§2Total: §a({count})\n"

  - type: show_group_info
    message: "§a- §6[{group}]§a | players ({count})\n"

  - type: show_help
    message: |
      §2-----Create-----§a
      §a/group create <groupName>
       
      §2-----Add-----§a
      /group add <player> <groupName>
      /group add <player> <groupName> <seconds>
        
      §2-----Remove-----§a
      /group remove <player>
      /group remove <player> <seconds>
       
      §2-----Info-----§a
      /group info
      /group info <groupName>
       
      §2-----List-----§a
      /group list